apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    # ALB kullanacağını ve Internet‑Facing açılacağını söylüyoruz
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing

    # Yalnızca HTTP (port 80)
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

    # Hedef service ve port
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP

    # (Opsiyonel) external‑dns kuruluysa DNS kaydı için
    # external-dns.alpha.kubernetes.io/hostname: argocd.ycsuisse.click

spec:
  rules:
    - host: argocd.ycsuisse.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
